name: dart_json_mapper
version: 2.2.16
description: >
  This package allows programmers to annotate Dart objects in order to
  serialize / deserialize them from / to JSON.
homepage: https://github.com/k-paxian/dart-json-mapper
environment:
  sdk: '>=3.7.2 <4.0.0'
dependencies:
  analyzer:
  build:
  build_config:
  intl:
  meta:
  path:
  reflectable:
    git:
      url: https://github.com/vlhttran/reflectable.git
      path: reflectable

  collection:
  pubspec_parse:
dev_dependencies:
  lints:
  build_runner:
